workflows:
  build_variant_1:
    name: "Build Variant 1"
    environment:
      vars:
        FLUTTER_APP_NAME: "kode"
        FLUTTER_APPLICATION_ID: "com.example.kode"
    scripts:
      - name: Update AndroidManifest.xml
        script: sed -i.bak "s/android:label=.*/android:label=\"$FLUTTER_APP_NAME\"/g" android/app/src/main/AndroidManifest.xml
      
      - name: Change Android package name
        script: |
          echo "android { defaultConfig { applicationId '${FLUTTER_APPLICATION_ID}' } }" > android/changePackage.gradle
          echo "apply from: rootProject.file('changePackage.gradle')" >> android/app/build.gradle
      
      - name: Install dependencies
        script: flutter packages pub get

      # Uncomment and adjust if needed
      # - name: Update Info.plist
      #   script: |
      #     plutil -replace CFBundleName -string "$FLUTTER_APP_NAME" ios/Runner/Info.plist

      # - name: Update build.gradle
      #   script: |
      #     sed -i '' 's/applicationId "[^"]*"/applicationId "$FLUTTER_APPLICATION_ID"/' android/app/build.gradle

      - name: Build APK
        script: flutter build apk --release --dart-define=FLUTTER_APP_NAME=$FLUTTER_APP_NAME --dart-define=FLUTTER_APPLICATION_ID=$FLUTTER_APPLICATION_ID

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

