definitions:
  env_vars: &env_vars
    S3_BUCKET_NAME: kode-staging # The name of your S3 bucket that have all of your clients assets.
    ANDROID_ASSETS_FOLDER: android_icons # The name of your folder in S3 bucket that have the client's Android assets from (/android/app/src/main/res/).
    IOS_ASSETS_FOLDER: ios_icons # The name of your folder in S3 bucket that have the client's iOS assets from (/ios/Runner/Assets.xcassets/).
    AWS_ACCESS_KEY_ID: AKIAWIXFRF6HSWDZOKVA # Replace with your actual AWS access key ID
    AWS_SECRET_ACCESS_KEY: zoWbHqixRswl0LxQCj9cn0EgjVmTVJW50dcFvonS # Replace with your actual AWS secret access key
    AWS_DEFAULT_REGION: eu-central-1 # Replace with your actual AWS region
  scripts:
    - &get_assets
      name: Get assets from AWS S3 bucket
      script: |
        ASSETS_FOLDER=assets_${CLIENT_ID}
        echo "ASSETS_FOLDER=$ASSETS_FOLDER" >> $CM_ENV
        
        aws s3 cp s3://$S3_BUCKET_NAME/$ASSETS_FOLDER.zip $ASSETS_FOLDER.zip
        unzip $ASSETS_FOLDER.zip -d $ASSETS_FOLDER

workflows:
  android-qa-workflow:
    name: Android client release QA
    instance_type: mac_mini_m1
    labels:
      - ${CLIENT_ID} # Helpful when you open your Codemagic's builds page 
      - APK
    environment:
      vars:
        <<: *env_vars
        CLIENT_ID: your_client_id_value # Ensure CLIENT_ID is defined here
    scripts:
      - *get_assets # Getting client assets from S3 bucket

      - name: Change Android app name
        script: sed -i.bak "s/android:label=.*/android:label=\"$APP_NAME\"/g" android/app/src/main/AndroidManifest.xml
     
      - name: Change Android package name
        script: |
          echo "android {  defaultConfig { applicationId '${PACKAGE_NAME}' }  }" > android/changePackage.gradle
          echo "apply from: rootProject.file('changePackage.gradle')" >> android/app/build.gradle
          
      - name: Change Android icons
        script: cp -r ./$ASSETS_FOLDER/$ANDROID_ASSETS_FOLDER/* ./android/app/src/main/res
          
      - name: Set client .env file
        script: echo $DOTENV | base64 --decode > assets/client.env
      
      - name: Set main image # An image that being used in this sample project
        script: cp -r ./$ASSETS_FOLDER/favicon.png assets/favicon.png
          
      - name: Install dependencies
        script: flutter packages pub get
      
      - name: Build release apk
        script: |
          flutter packages pub get
          flutter build apk --release
    artifacts: 
      - build/**/outputs/**/*.aab
    publishing:
      email: 
        recipients:
          - sarah7amr@gmail.com
